import Head from 'next/head'
import Image from 'next/image'
import signInImage from './../public/assets/images/signIn.png';
import styles from  '../styles/homeLayout.module.scss';
import Logo from '@/components/logo/Logo'


export default function HomeLayout({ children } : any) {
    return (   
    <>
      <Head>
        <title>Login | Register</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.homeLayout}>
        {/* Left side */}
        <div className={styles.homeLayout__left}>
          <Logo />
          <div className={styles.homeLayout__left_imageContainer}>
            <Image 
              src={signInImage} 
              alt='sign in image'  
              className={styles.homeLayout__left_image}
              width={600}
              height={337.57}
            />
          </div>
        </div>
        {/* Right side */}
        <div className={styles.homeLayout__right}>
          {children}
        </div>
      </main>
    </>
    )
  }